# @package _global_
defaults:
 - _self_

target: ph
task: regression

data_base: /data/ph/features_fold_0
fold: 0
num_classes: 1
threshold: 25
median: 40
bin_features_static: 86
weights:
live_loading: True
delete_segmentation: False
balanced_accuracy: False
eval_metric: mae
data_orig:
low_data_splits: ['']

# num of features
num_cat: 1
num_con: 35

labels_train: labels_reg_train.pt
labels_val: labels_reg_val.pt

data_train_imaging: train_paths.pt
data_val_imaging: val_paths.pt

# data_train_imaging: train_images_all_views.pt
# data_val_imaging: val_images_all_views.pt

data_train_tabular: ph_train.csv
data_val_tabular: ph_val.csv

field_lengths_tabular: tabular_lengths.pt


data_train_eval_tabular: ph_train.csv
labels_train_eval_tabular: labels_reg_train.pt

data_val_eval_tabular: ph_val.csv
labels_val_eval_tabular: labels_reg_val.pt

data_test_eval_tabular: ph_test.csv
labels_test_eval_tabular: labels_reg_test.pt


data_train_eval_imaging: train_paths.pt
labels_train_eval_imaging: labels_reg_train.pt

data_val_eval_imaging: val_paths.pt
labels_val_eval_imaging: labels_reg_val.pt

data_test_eval_imaging: test_paths.pt
labels_test_eval_imaging: labels_reg_test.pt

feature_names: feature_names.json
feature_norms: feature_norms.npz

data_train_tabular_bin: train_bin_mdlp.csv
data_val_tabular_bin: val_bin_mdlp.csv
data_test_tabular_bin: test_bin_mdlp.csv
binarized_column_names: binarized_column_names_mdlp.json
binarized_column_lengths: binarized_column_lengths_mdlp.json